## 数据源配置
spring.datasource:
  url: jdbc:mysql://localhost:3381/springbootdb?useUnicode: true&characterEncoding: utf8
  username: root
  password: root
  driver-class-name: com.mysql.jdbc.Driver

## Mybatis 配置
mybatis:
  typeAliasesPackage: io.hischoolboy
  mapperLocations: classpath:mapper/*.xml

## Redis 配置
## Redis数据库索引（默认为0）
spring.redis: 
  database: 0
## Redis服务器地址
  host: 192.168.31.217
## Redis服务器连接端口
  port: 6379
## Redis服务器连接密码（默认为空）
  password: 
## 连接池最大连接数（使用负值表示没有限制）
  pool.max-active: 8
## 连接池最大阻塞等待时间（使用负值表示没有限制）
  pool.max-wait: -1
## 连接池中的最大空闲连接
  pool.max-idle: 8
## 连接池中的最小空闲连接
  pool.min-idle: 0
## 连接超时时间（毫秒）
  timeout: 300